protocol.version=0.2
minecraft.version=26.2
pack.id=82c70131-0d1c-330f-b91c-65cd253ffda2
font.id=tomblock:hud_protocol
marker.red=250
actionbar.baseline.offset=59
encoded.ascent=7
bar.cell.advance=17
bar.cell.advance.status-health-bar=9
bar.cell.advance.status-energy-bar=9
glyph.lab_icon=E000
glyph.bar_filled=E001
glyph.bar_empty=E002
glyph.panel=E003
glyph.status_heart=E004
glyph.status_energy=E005
glyph.status_health_bar_filled=E006
glyph.status_health_bar_empty=E007
glyph.status_energy_bar_filled=E008
glyph.status_energy_bar_empty=E009
glyph.bar_joiner=E00A
palette.0=FFFFFF
palette.1=FF4055
palette.2=00E6C3
palette.3=F2AE32
palette.4=AAAAAA
palette.5=FFAA00
palette.6=FF5555
palette.7=FFFF55
palette.8=55FF55
palette.9=00AAAA
palette.10=555555
